version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
mkdocs:
  configuration: mkdocs.yml
python:
  version: "3.11"
  install:
    - pip install mkdocs-windmill-dark markdown-include mkdocstrings



