site_name: Decyphertek.io
theme:
  name: material
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - attr_list
  - md_in_html

nav:
    - Home: index.md
    - Products:
        - Product One: products/product_one.md
        #- Product Two: products/product_two.md
    #- Tech-Notes:
        #- Tech_One: technotes/service_one.md
        #- Service Two: services/service_two.md
    #- About: about.md
    #- Contact: contact.md
