site_name: Decyphertek.io
theme:
  name: material
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - attr_list
  - md_in_html

nav:
    - Home: index.md
    - AWS Marketplace:
        - Debian Basics: products/debian-security.md
        - Flatcar Basics: products/flatcar-security.md
        - Gitea: products/gitea.md
        - Firezone: products/firezone.md
        - Mautic: products/mautic.md
        - Nodered: products/nodered.md
        - Odoo: products/odoo.md
        - Pritunl: products/pritunl.md
        - Uptime Kuma: products/uptime-kuma.md
    - Tech Notes:
        - Aide: technotes/Aide.md 
        - Android Roms: technotes/Android-Roms.md 
        - Ansible: technotes/Ansible.md 
        - App Write: technotes/App-Write.md 
        - Arkime: technotes/Arkime.md 
        - Auditd: technotes/Auditd.md 
        - Authelia: technotes/Authelia.md 
        - Autogpt: technotes/Autogpt.md 
        - AWS CLI: technotes/AWS-CLI.md 
        - Balena Etcher: technotes/Balena-Etcher.md 
        - Beekeeper Studio: technotes/Beekeeper-Studio.md 
        - Bespoke: technotes/Bespoke-Synth.md 
        - Briar: technotes/Briar.md 
        - Caldera: technotes/Caldera.md 
        - Cap Analysis: technotes/Cap-Analysis.md 
        - CheckMK: technotes/CheckMK.md 
        - ChirpStack: technotes/ChirpStack.md 
        - CIS Controls: technotes/CIS-Controls.md 
        - CIS / OSCAP: technotes/CIS-OSCAP.md 
        - ClamAV: technotes/ClamAV.md 
        - Cloudinit: technotes/Cloud-Init.md 
        - CloudQuery: technotes/Cloud-query.md 
        - CloudPanel: technotes/Cloudpanel.md 
        - Crowdsec: technotes/Crowdsec.md 
        - Debian Medical: technotes/DebMed.md 
        - Deja Dup: technotes/Deja-Dup.md 
        - Dependency Track: technotes/Dependency-Track.md 
        - Docker: technotes/Docker.md 
        - EFF: technotes/EFF.md 
        - ESIM: technotes/ESIM.md 
        - Exodus Privacy: technotes/Exodus-Privacy.md 
        - Firezone: technotes/FireZone.md 
        - Flutter: technotes/Flutter.md 
        - Fog Project: technotes/Fog-Project.md 
        - Foreman: technotes/Foreman.md 
        - FreedomBox: technotes/FreedomBox.md 
        - FreedomFI: technotes/FreedomFi.md 
        - FreeIPA: technotes/FreeIPA.md 
        - FreeLan: technotes/Freelan.md
        - FreeScout: technotes/FreeScout.md 
        - GIS Workstation: technotes/GIS-Workstation.md 
        - Github: technotes/Github.md 
        - Gitpod: technotes/Gitpod.md 
        - GNS3: technotes/GNS3.md 
        - Greylog: technotes/Greylog.md 
        - IDS Tower: technotes/IdsTower.md 
        - Incus: technotes/Incus.md
        - Instrucitonal Gifs: technotes/Instructional-Gifs.md 
        - Internet in A Box: technotes/Internet-In-A-Box.md 
        - Jenkins: technotes/Jenkins.md 
        - Jupyterhub: technotes/Jupyterhub.md 
        - Keycloak: technotes/Keycloak.md 
        - Kubernetes: technotes/Kubernetes.md 
        - Kubesphere: technotes/KubeSphere.md 
        - LEMP Stack: technotes/LEMP-Stack.md 
        - Libre Wolf: technotes/LibreWolf.md 
        - Linux: technotes/Linux.md 
        - LXC: technotes/LXC.md
        - LXD: technotes/LXD.md
        - ManageIQ: technotes/Manage-iq.md 
        - Mastadon: technotes/Mastadon.md 
        - Meshcentral: technotes/Meshcentral.md 
        - MISP: technotes/Misp.md 
        - MIST-IO: technotes/Mist-io.md 
        - MyCroft: technotes/Mycroft-ai.md 
        - MySQL: technotes/MySql.md 
        - Nginx: technotes/Nginx.md 
        - Nmap: technotes/Nmap.md 
        - NodeRed: technotes/NodeRed.md 
        - Nomad: technotes/nomad.md 
        - NtopNG: technotes/NtopNg.md 
        - Odoo: technotes/Odoo.md 
        - OneDev: technotes/OneDev.md 
        - OpenAI: technotes/OpenAI.md 
        - OpenHab: technotes/Openhab.md 
        - OpenSearch: technotes/Opensearch.md 
        - OSSEC: technotes/OSSEC.md 
        - Packer: technotes/Packer.md 
        - Pulumi: technotes/Pulumi.md 
        - Qgis: technotes/Qgis.md
        - Quad9: technotes/Quad9.md 
        - Read The Docs: technotes/Read-The-Docs.md 
        - RescueZilla: technotes/RescueZilla.md 
        - RND: technotes/RND.md 
        - ROS: technotes/ROS.md 
        - Rport: technotes/Rport.md 
        - Secure Delete: technotes/Secure-Delete.md 
        - Signal Desktop: technotes/Signal-Desktop.md 
        - SSSD: technotes/SSSD.md 
        - Stack Storm: technotes/Stackstorm.md 
        - Syslinux: technotes/Syslinux.md 
        - System Rescue: technotes/System-Rescue.md 
        - Tailscale: technotes/Tailscale.md 
        - Taskel: technotes/Tasksel.md 
        - TCPdump: technotes/Tcpdump.md 
        - Tech Culture: technotes/Tech-Culture.md 
        - Technitium: technotes/Technitium.md 
        - Terraform: technotes/Terraform.md 
        - UFW: technotes/UFW.md 
        - Unattended Upgrades: technotes/Unattended-Upgrades.md 
        - Web Goat: technotes/WebGoat.md 
        - Whonix: technotes/Whonix.md 
        - Windows: technotes/Windows.md 
        - Wordpress: technotes/WordPress.md 
        - Zentyal: technotes/Zentyal.md 
        - Zoneminder: technotes/Zoneminder.md
    - Contact: contact.md
