[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "decyphertek-io"
authors = [{name = "decyphertek", email = "adminotaur@decyphertek.io"}]
dynamic = ["version", "description"]